name: Untold
main: com.depths.untold.Untold
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: 0.1
description: Provides additional events to the server
depend: []
authors: [Tim, Ben]
commands:
  untold:
    description: Allows you to build up your town
  u:
    description: Allows you to build up your town